export const genders = [
    {label: "Cisgénero", value: "Cisgénero"},
    {label: "Transgénero", value: "Transgénero"},
    {label: "No binario", value: "No binario"},
    {label: "No binario", value: "No binario"},
    {label: "Género fluido", value: "Género fluido"},
    {label: "Género fluido", value: "Género fluido"},
    {label: "Agénero", value: "Agénero"},
    {label: "Agénero", value: "Agénero"},
    {label: "Demigénero", value: "Demigénero"},
    {label: "Genderqueer", value: "Genderqueer"},
];

export const options = [
    {id: 1, label: "Arm and leg sleeves ('armbinders')"},
    {id: 2, label: "Breast Bondage"},
    {id: 3, label: "Blindfolds"},
    {id: 4, label: "Bondage - Light"},
    {id: 5, label: "Bondage - Heavy"},
    {id: 6, label: "Bondage - All day/multi day"},
    {id: 7, label: "Cages/Cells/Closets"},
    {id: 8, label: "Chains (bound with)"},
    {id: 9, label: "Chastity device/belts"},
    {id: 10, label: "Collars - Worn in private"},
    {id: 11, label: "Collars - Worn in public"},
    {id: 12, label: "Cuffs - Leather"},
    {id: 13, label: "Cuffs - Metal"},
    {id: 14, label: "Cuffs - Handcuff Style"},
    {id: 15, label: "Ear Plus (sound deprivation)"},
    {id: 16, label: "Gags - Ball"},
    {id: 17, label: "Gags - Bit"},
    {id: 18, label: "Gags - Cloth"},
    {id: 19, label: "Gags - Inflatable"},
    {id: 21, label: "Gags - Phallic"},
    {id: 22, label: "Gags - Ring"},
    {id: 23, label: "Gags - Tape"},
    {id: 24, label: "Harnessing - Leather"},
    {id: 25, label: "Harnessing - Rope"},
    {id: 26, label: "Hoods (full head)"},
    {id: 27, label: "Immobilisation"},
    {id: 28, label: "Leash"},
    {id: 29, label: "Leather restraints"},
    {id: 30, label: "Manacles & Irons"},
    {id: 31, label: "Mummification"},
    {id: 32, label: "Muzzles"},
    {id: 33, label: "Rope bondage - Simple"},
    {id: 34, label: "Rope bondage - Intricate (Shibari)"},
    {id: 35, label: "Spreaded Bars"},
    {id: 36, label: "Stocks (head and hands)"},
    {id: 37, label: "Straight Jackets"},
    {id: 38, label: "Suspension - Upright"},
    {id: 39, label: "Suspension - Horizontal"},
    {id: 40, label: "Suspension - Inverted"},
    {id: 41, label: "Sleep sacks"},
    {id: 42, label: "Boot worship"},
    {id: 43, label: "Cock worship"},
    {id: 44, label: "Corsets"},
    {id: 45, label: "Cross dressing"},
    {id: 46, label: "Diapers"},
    {id: 47, label: "Foot worship"},
    {id: 48, label: "Gas Masks"},
    {id: 49, label: "High heels (wearing)"},
    {id: 50, label: "High heels Worship)"},
    {id: 51, label: "Leather (wearing)"},
    {id: 52, label: "Lingerie (wearing)"},
    {id: 53, label: "Pussy worship"},
    {id: 54, label: "Rubber / latex clothing (wearing)"},
    {id: 55, label: "Slutty clothing"},
    {id: 56, label: "Spandex clothing"},
    {id: 57, label: "Chamber pot use"},
    {id: 58, label: "Creampie"},
    {id: 59, label: "Cum - In ass"},
    {id: 60, label: "Cum - In mouth"},
    {id: 61, label: "Cum - In vagina"},
    {id: 62, label: "Cum - On body"},
    {id: 63, label: "Cutting - Blood play"},
    {id: 64, label: "Golden showers (urinate on)"},
    {id: 65, label: "Human Toilet"},
    {id: 66, label: "Injections (Saline)"},
    {id: 67, label: "Milking (made to produce breast milk)"},
    {id: 68, label: "Pearl necklace (cum on chest/throat)"},
    {id: 69, label: "Pearl shower (cum on face)"},
    {id: 70, label: "Rimming (oral/anal play)"},
    {id: 71, label: "Scat (brown showers)"},
    {id: 72, label: "Swallowing semen"},
    {id: 73, label: "Swallowing urine"},
    {id: 74, label: "Forced dressing"},
    {id: 75, label: "Forced feminization"},
    {id: 76, label: "Forced homosexuality"},
    {id: 77, label: "Forced masturbatuib"},
    {id: 78, label: "Forced nudity"},
    {id: 79, label: "Forced servitude"},
    {id: 80, label: "Humiliation in private"},
    {id: 91, label: "Humiliation in public"},
    {id: 92, label: "Lecturing for misbehaviours"},
    {id: 93, label: "Shaving head hair"},
    {id: 94, label: "Shaving or depilation of body hair"},
    {id: 95, label: "Standing in corner (punishment)"},
    {id: 96, label: "Verbal humiliation"},
    {id: 97, label: "Breast whipping"},
    {id: 98, label: "Caning - English"},
    {id: 99, label: "Caning - Sensation"},
    {id: 100, label: "Face slapping"},
    {id: 101, label: "Punching"},
    {id: 102, label: "Pussy punching"},
    {id: 103, label: "Pussy kicking"},
    {id: 104, label: "Pussy spanking (smacking)"},
    {id: 105, label: "Pussy whipping"},
    {id: 106, label: "Riding crops"},
    {id: 107, label: "Spanking - Hairbrush"},
    {id: 108, label: "Spanking - Hand"},
    {id: 109, label: "Spanking - Leather slappers"},
    {id: 110, label: "Spanking - (OTK) Over the knee"},
    {id: 111, label: "Whipping - Belt"},
    {id: 112, label: "Whipping - Cat o' 9 tails"},
    {id: 113, label: "Whipping - Flogger"},
    {id: 114, label: "Whipping - Single tail"},
    {id: 115, label: "Wrestling"},
    {id: 116, label: "Fantasy gang rape"},
    {id: 117, label: "Group play - Multiple men 'gang bang'"},
    {id: 118, label: "Group play - Multiple womeen & men"},
    {id: 119, label: "Group play - Orgy"},
    {id: 120, label: "Shared (given to another only temp)"},
    {id: 121, label: "Swapping (with one other couple)"},
    {id: 122, label: "Swinging (multiple couples)"},
    {id: 123, label: "Branding"},
    {id: 124, label: "Scarification (cutting, making scars)"},
    {id: 125, label: "Tattooing (inking)"},
    {id: 126, label: "Abandonment (fantasy)"},
    {id: 127, label: "Age play (not pedophilia)"},
    {id: 128, label: "Animal roleplay"},
    {id: 129, label: "Auctioned for charity"},
    {id: 130, label: "Fear play"},
    {id: 131, label: "Human puppy-dog play"},
    {id: 132, label: "Infantilism (baby play)"},
    {id: 133, label: "Initiation rites"},
    {id: 134, label: "Interrogations"},
    {id: 135, label: "Kidnapping"},
    {id: 136, label: "Medical scenes"},
    {id: 137, label: "Name change"},
    {id: 138, label: "Pony play"},
    {id: 139, label: "Psych ward play"},
    {id: 140, label: "Prison scenes"},
    {id: 141, label: "Prostitution fantasy"},
    {id: 142, label: "Religious scenes"},
    {id: 143, label: "Schoolroom scenes"},
    {id: 144, label: "Switching roles (Top/bottom)"},
    {id: 145, label: "Total Power Exchange (TPE)"},
    {id: 146, label: "Other roleplaying"},
    {id: 147, label: "Abrasion (scraping, sanding)"},
    {id: 148, label: "Asphyxiation"},
    {id: 149, label: "Ball stretching"},
    {id: 150, label: "Biting (being bitten)"},
    {id: 151, label: "Beating hard"},
    {id: 152, label: "Beating soft"},
    {id: 153, label: "Breath control (Choking)"},
    {id: 154, label: "Breath control (Mild restruction)"},
    {id: 155, label: "Clamps - Labia/clit area"},
    {id: 156, label: "Clothespins"},
    {id: 157, label: "Dilation"},
    {id: 158, label: "Electricity - Internal (egg or probe)"},
    {id: 159, label: "Electricity - TENS unit"},
    {id: 160, label: "Electricity - Violet Wand"},
    {id: 161, label: "Enemas - For cleansing"},
    {id: 162, label: "Enemas - Retention/training"},
    {id: 163, label: "Finger claws"},
    {id: 164, label: "Fire cupping"},
    {id: 165, label: "Fire play"},
    {id: 166, label: "Hair pulling"},
    {id: 167, label: "Hot wax - Dripping on body/genitals"},
    {id: 168, label: "Hot wax - Hair removal"},
    {id: 169, label: "Ice cubes"},
    {id: 170, label: "Kicking"},
    {id: 171, label: "Knife play (blood drawn)"},
    {id: 172, label: "Knife play (no blood)(sensation)"},
    {id: 173, label: "Needle play"},
    {id: 174, label: "Nipple clamps"},
    {id: 175, label: "Nipple piercing"},
    {id: 176, label: "Nipple play - Pulls, Tugs, Twists"},
    {id: 177, label: "Pain - Mild"},
    {id: 178, label: "Pain - Severe"},
    {id: 179, label: "Piercing (permanent)"},
    {id: 180, label: "Piercing (temporary)"},
    {id: 181, label: "Punishment scene"},
    {id: 182, label: "Riding the horse (crotch torture)"},
    {id: 183, label: "Scratching"},
    {id: 184, label: "Sensory deprivation"},
    {id: 185, label: "Strapping (full body beating)"},
    {id: 186, label: "Suction cups"},
    {id: 187, label: "Teasing"},
    {id: 188, label: "Tickling"},
    {id: 189, label: "Vampire gloves"},
    {id: 190, label: "Water torture (waterboarding)"},
    {id: 191, label: "Wartenburg pinwheel"},
    {id: 192, label: "Zippers - Clamps"},
    {id: 193, label: "Zippers - Needdles"},
    {id: 194, label: "Examinations"},
    {id: 195, label: "Exhibitionism (friends)"},
    {id: 196, label: "Exhibitionism (strangers)"},
    {id: 197, label: "Forced nudity (private)"},
    {id: 198, label: "Forced nudity (around others)"},
    {id: 199, label: "Modeling for erotic photos"},
    {id: 200, label: "Outdoor scenes"},
    {id: 201, label: "Video (watching others)"},
    {id: 202, label: "Video (recordings of you)"},
    {id: 203, label: "Voyeurism (watching others)"},
    {id: 204, label: "Voyeurism (your Dom w/others )"},
    {id: 205, label: "Anal beads"},
    {id: 206, label: "Anal play"},
    {id: 207, label: "Anal plugs - Small"},
    {id: 208, label: "Anal Anal plugs - Medium"},
    {id: 209, label: "Anal Anal plugs - Large"},
    {id: 210, label: "Anal Anal plugs - Public, under clothes"},
    {id: 211, label: "Anal sex"},
    {id: 212, label: "Bestiality (sex with animals)"},
    {id: 213, label: "Breast fucking"},
    {id: 214, label: "Catherization"},
    {id: 215, label: "Cunnilingus (giving oral to a woman"},
    {id: 216, label: "Cunnilingus (receiving oral"},
    {id: 217, label: "Dildos - Anal"},
    {id: 218, label: "Dildos - Oral"},
    {id: 219, label: "Dildos - Vaginal"},
    {id: 220, label: "Double penetration"},
    {id: 221, label: "Fantasy rape play"},
    {id: 222, label: "Fellatio (oral sex on a penis)"},
    {id: 223, label: "Fisting - Anal"},
    {id: 224, label: "Fisting - Vaginal"},
    {id: 225, label: "Genital sex"},
    {id: 226, label: "Masturbation"},
    {id: 227, label: "Orgasm control"},
    {id: 228, label: "Orgasm denial"},
    {id: 229, label: "Sexual deprivation"},
    {id: 230, label: "Sounding"},
    {id: 231, label: "Speculums"},
    {id: 232, label: "Strap-on-dildos (sucking on)"},
    {id: 233, label: "Strap-on-dildos (penetrated by)"},
    {id: 234, label: "Strap-on-dildos (wearing)"},
    {id: 235, label: "Triple penetration"},
    {id: 236, label: "Vibrator - Anal"},
    {id: 237, label: "Vibrator - External genital"},
    {id: 238, label: "Vibrator - Internal genital"},

]